image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-certificate-microservice:
  stage: build
  script:
    gradle certificate-microservice:assemble certificate-microservice:testClasses

checkStyle-certificate-microservice:
  stage: staticAnalysis
  script:
    gradle certificate-microservice:checkstyleMain certificate-microservice:checkStyleTest
  allow_failure: true


PMD-certificate-microservice:
  stage: staticAnalysis
  script:
    gradle certificate-microservice:pmdMain
  allow_failure: true

test-certificate-microservice:
  stage: test
  script:
    - gradle certificate-microservice:test certificate-microservice:jacocoTestReport
    - cat certificate-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
